name: button_animations
description: Highly customizable animated buttons

version: 1.0.1
homepage: https://github.com/anshrathod/button_animations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
