name: button_animations
description: A package that helps you make highly customizable animated 3d-buttons.

version: 1.0.1+2
homepage: https://github.com/anshrathod/button_animations

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
